Grid : Set column with Conf
naturalsolutions/ecoReleve-Data pull request #371
Opened 2016-10-27 15:45 UTC by romfabbro

2016-11-07 10:35 UTC, Matheo13 commented
SSMS:
Msg 207, Niveau 16, État 1, Ligne 15
Nom de colonne non valide : 'ColumnParams'.

2016-11-08 08:22 UTC, romfabbro commented
you have an sql pip to pass which tagged by "db update"

2016-11-08 08:22 UTC, romfabbro commented
see the commit only on commit

2016-11-08 08:30 UTC, Matheo13 commented
Ok I had to launch first 

ALTER Table ModuleGrids 
ADD ColumnParams varchar(250)

then the rest.

I'll test it right now

2016-11-08 08:46 UTC, Matheo13 requested changes

2016-11-08 08:46 UTC, Matheo13 commented on Front/app/ns_modules/ns_grid/grid.view.js
> +              //_this.gridOptions.api.sizeColumnsToFit();
Don't comment it. It's used somewhere else. I don't have rights on your branch.
Column's size must be defined in base, then auto fit from those sizes.

2016-11-08 08:47 UTC, Matheo13 commented
Then it's fine.

2016-11-08 15:16 UTC, romfabbro commented on Front/app/ns_modules/ns_grid/grid.view.js
> +              //_this.gridOptions.api.sizeColumnsToFit();
done

2016-11-08 16:27 UTC, Matheo13 commented
minWidth to 100 insted of 50 in wouldn't be better?

2016-11-08 16:27 UTC, Matheo13 approved these changes

2016-11-08 16:27 UTC, merged